// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShoppingCartApp.Models.Data;

#nullable disable

namespace ShoppingCartApp.Migrations
{
    [DbContext(typeof(ShoppingCartDBContext))]
    [Migration("20251026081452_Initial Build Shopping Cart App")]
    partial class InitialBuildShoppingCartApp
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CampingStoreAPP.Models.AppUserId", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AppUsers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "Admin",
                            PasswordHash = "$2a$11$5ThwsSS2DE2o3Wo6EjcpHu2vBE/w6CEwRBfQq2ALVR1nq53jk6o1O"
                        });
                });

            modelBuilder.Entity("CampingStoreAPP.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A light green apple with a crisp, juicy texture and a distinctively tart flavor.",
                            Price = 5.5,
                            ProductName = "Granny Smith Apples",
                            Unit = "1kg"
                        },
                        new
                        {
                            Id = 2,
                            Description = "A common, red, juicy fruit used in salads, sauces, and cooking.",
                            Price = 5.9000000000000004,
                            ProductName = "Fresh tomatoes",
                            Unit = "500g"
                        },
                        new
                        {
                            Id = 3,
                            Description = "A large, edible fruit with a hard rind and sweet, juicy deep red to pink flesh, known for its high water content.",
                            Price = 6.5999999999999996,
                            ProductName = "Watermelon",
                            Unit = "Whole"
                        },
                        new
                        {
                            Id = 4,
                            Description = "A long, green-skinned fruit with crisp, cool, and mildly flavored flesh, often used in salads.",
                            Price = 1.8999999999999999,
                            ProductName = "Cucumber",
                            Unit = "1 whole"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Potatoes with a pink, smooth skin and creamy white, low-starch flesh, ideal for roasting or boiling.",
                            Price = 4.0,
                            ProductName = "Red potato washed",
                            Unit = "1kg"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Sweet and creamy bananas grown using the Ecoganic® farming system, dipped in a distinctive red food-grade wax.",
                            Price = 4.9000000000000004,
                            ProductName = "Red tipped bananas",
                            Unit = "1kg"
                        },
                        new
                        {
                            Id = 7,
                            Description = "An onion with purplish-red skin and a sweeter, milder flavor, often used raw in salads.",
                            Price = 3.5,
                            ProductName = "Red onion",
                            Unit = "1kg"
                        },
                        new
                        {
                            Id = 8,
                            Description = "A root vegetable, typically orange, with a crisp texture and sweet, earthy flavor, high in beta-carotene.",
                            Price = 2.0,
                            ProductName = "Carrots",
                            Unit = "1kg"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Characterized by a tight head of crisp, light green leaves and a neutral taste, popular for salads.",
                            Price = 2.5,
                            ProductName = "Iceburg Lettuce",
                            Unit = "1"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Traditional sliced bread made with 60% wholemeal wheat flour, a source of wholegrains, fibre, and protein.",
                            Price = 3.7000000000000002,
                            ProductName = "Helga's Wholemeal",
                            Unit = "1"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Chicken meat from birds allowed to roam freely outdoors for at least part of the day.",
                            Price = 7.5,
                            ProductName = "Free range chicken",
                            Unit = "1kg"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Six large, free-range eggs produced by hens that roam with access to the outdoors.",
                            Price = 3.6000000000000001,
                            ProductName = "Manning Valley 6-pk",
                            Unit = "6 eggs"
                        },
                        new
                        {
                            Id = 13,
                            Description = "Milk containing only the A2 type of beta-casein protein, with a reduced fat content (light).",
                            Price = 2.8999999999999999,
                            ProductName = "A2 light milk",
                            Unit = "1 litre"
                        },
                        new
                        {
                            Id = 14,
                            Description = "A single-serve Greek yogurt, typically high in protein, with a sweet strawberry flavor.",
                            Price = 1.5,
                            ProductName = "Chobani Strawberry Yoghurt",
                            Unit = "1"
                        },
                        new
                        {
                            Id = 15,
                            Description = "A spreadable blend of butter and vegetable oil (like rapeseed oil) with a slightly salty taste.",
                            Price = 5.0,
                            ProductName = "Lurpak Salted Blend",
                            Unit = "250g"
                        },
                        new
                        {
                            Id = 16,
                            Description = "A block of Bega brand cheese, typically a mature or vintage cheddar, known for its strong, full flavor.",
                            Price = 4.0,
                            ProductName = "Bega Farmers Tasty",
                            Unit = "250g"
                        },
                        new
                        {
                            Id = 17,
                            Description = "Small, round, semisoft cheese portions encased in a distinctive red wax shell.",
                            Price = 4.2000000000000002,
                            ProductName = "Babybel Mini",
                            Unit = "100g"
                        },
                        new
                        {
                            Id = 18,
                            Description = "Extra Virgin Olive Oil from the Cobram Estate brand, known for its high quality.",
                            Price = 8.0,
                            ProductName = "Cobram EVOO",
                            Unit = "375ml"
                        },
                        new
                        {
                            Id = 19,
                            Description = "A classic, smooth, condensed soup made primarily from sun-ripened tomatoes.",
                            Price = 2.5,
                            ProductName = "Heinz Tomato Soup",
                            Unit = "535g"
                        },
                        new
                        {
                            Id = 20,
                            Description = "Tuna chunks preserved in sunflower oil or brine, rich in protein and a source of omega-3 fatty acids.",
                            Price = 1.5,
                            ProductName = "John West Tuna can",
                            Unit = "95g"
                        },
                        new
                        {
                            Id = 21,
                            Description = "A brand of milk chocolate known for its creamy texture.",
                            Price = 5.0,
                            ProductName = "Cadbury Dairy Milk",
                            Unit = "200g"
                        },
                        new
                        {
                            Id = 22,
                            Description = "A globally recognized carbonated soft drink with a characteristic sweet, caramel-colored, bubbly flavor.",
                            Price = 2.8500000000000001,
                            ProductName = "Coca Cola",
                            Unit = "2 litre"
                        },
                        new
                        {
                            Id = 23,
                            Description = "Crinkle cut potato chips with a classic original (salted) flavor.",
                            Price = 3.29,
                            ProductName = "Smith's Original Share Pack Crisps",
                            Unit = "170g"
                        },
                        new
                        {
                            Id = 24,
                            Description = "Rectangular portions of white fish (often cod or pollock) coated in breadcrumbs, popular for quick meals.",
                            Price = 4.5,
                            ProductName = "Birds Eye Fish Fingers",
                            Unit = "375g"
                        },
                        new
                        {
                            Id = 25,
                            Description = "A brand of orange juice, likely a blend or juice from concentrate.",
                            Price = 6.0,
                            ProductName = "Berri Orange Juice",
                            Unit = "2 litre"
                        },
                        new
                        {
                            Id = 26,
                            Description = "A thick, dark-brown Australian spread made from brewer's yeast extract with a strong, salty, umami flavor.",
                            Price = 6.0,
                            ProductName = "Vegemite",
                            Unit = "380g"
                        },
                        new
                        {
                            Id = 27,
                            Description = "A type of baked savory biscuit known for their crunchy texture and baked-in cheddar cheese flavor.",
                            Price = 3.0,
                            ProductName = "Cheddar Shapes",
                            Unit = "175g"
                        },
                        new
                        {
                            Id = 28,
                            Description = "A toothpaste offering complete oral health protection, including against plaque, tartar, and gingivitis.",
                            Price = 4.5,
                            ProductName = "Colgate Total Toothpaste Original",
                            Unit = "110g"
                        },
                        new
                        {
                            Id = 29,
                            Description = "A low GI malt powder drink with a delicious choc malt flavor, made from milk powder, malt barley, sugar, and cocoa.",
                            Price = 4.9000000000000004,
                            ProductName = "Milo Choclate Malt",
                            Unit = "460g"
                        },
                        new
                        {
                            Id = 30,
                            Description = "Breakfast cereal made from 97% certified organic whole wheat, low in fat and sugar, and a source of fibre.",
                            Price = 4.0,
                            ProductName = "Weet Bix Saniatarium Organic",
                            Unit = "750g"
                        },
                        new
                        {
                            Id = 31,
                            Description = "Dark chocolate expertly crafted with 70% cocoa, boasting deep roasted cocoa flavors and a smooth, refined texture.",
                            Price = 3.0,
                            ProductName = "Lindt Excellence 70% Cocoa Block",
                            Unit = "100g"
                        },
                        new
                        {
                            Id = 32,
                            Description = "An iconic Australian chocolate biscuit: two malted biscuits separated by cream and coated in chocolate.",
                            Price = 3.7999999999999998,
                            ProductName = "Original Tim Tams Choclate",
                            Unit = "200g"
                        },
                        new
                        {
                            Id = 33,
                            Description = "A deliciously creamy, full-flavored, block-style cream cheese made with fresh milk and real cream.",
                            Price = 4.0,
                            ProductName = "Philadeplhia Original Cream Cheese",
                            Unit = "250g"
                        },
                        new
                        {
                            Id = 34,
                            Description = "A full-bodied, richly aromatic instant coffee with a rounded, balanced medium roast flavor.",
                            Price = 8.5,
                            ProductName = "Moccana Classic Instant Medium Roast",
                            Unit = "100g"
                        },
                        new
                        {
                            Id = 35,
                            Description = "Pure Australian honey packaged in a convenient squeeze-bottle dispenser.",
                            Price = 6.5,
                            ProductName = "Capilano Squeezeable Honey",
                            Unit = "375g"
                        },
                        new
                        {
                            Id = 36,
                            Description = "An iconic smooth and creamy hazelnut chocolate spread, crafted with roasted hazelnuts and rich cocoa.",
                            Price = 4.0,
                            ProductName = "Nutella jar",
                            Unit = "220g"
                        },
                        new
                        {
                            Id = 37,
                            Description = "A popular rectangular sweet biscuit from Arnott's, known for its rich, buttery, and melt-in-your-mouth shortbread texture.",
                            Price = 3.0,
                            ProductName = "Arnott's Scotch Finger",
                            Unit = "250g"
                        },
                        new
                        {
                            Id = 38,
                            Description = "A creamy white cheese with a porous texture, a sharp, salty, and milky flavor, often sold in brine.",
                            Price = 4.5,
                            ProductName = "South Cape Greek Feta",
                            Unit = "150g"
                        },
                        new
                        {
                            Id = 39,
                            Description = "A pasta sauce featuring whole Italian cherry tomatoes and fresh basil in a soffritto base of carrots, onions, and celery.",
                            Price = 6.0,
                            ProductName = "Sacla Pasta Tomato Basil Sauce",
                            Unit = "680g"
                        },
                        new
                        {
                            Id = 40,
                            Description = "English style leg ham, cured and seasoned, offering a savory deli meat.",
                            Price = 3.5,
                            ProductName = "Primo English Ham",
                            Unit = "100g"
                        },
                        new
                        {
                            Id = 41,
                            Description = "Bacon made from the back loin, cured and smoked, with a rich sweet and salty taste, and naturally rindless.",
                            Price = 7.0,
                            ProductName = "Primo Short cut rindless Bacon",
                            Unit = "250g"
                        },
                        new
                        {
                            Id = 42,
                            Description = "Canned pineapple pieces preserved in natural pineapple juice.",
                            Price = 1.5,
                            ProductName = "Golden Circle Pineapple Pieces in natural juice",
                            Unit = "425g"
                        },
                        new
                        {
                            Id = 43,
                            Description = "A thin, flat ribbon style pasta (No. 1), made from Durum Wheat Semolina, great with pesto or cream-based sauces.",
                            Price = 3.0,
                            ProductName = "San Remo Linguine Pasta No 1",
                            Unit = "500g"
                        });
                });

            modelBuilder.Entity("CampingStoreAPP.Models.ShoppingCart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FinalisedDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("Total")
                        .HasColumnType("float");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ShoppingCarts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppUserId = 1,
                            Total = 0.0
                        });
                });

            modelBuilder.Entity("CampingStoreAPP.Models.ShoppingCartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("ShoppingCartId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("ShoppingCartId");

                    b.ToTable("ShoppingCartItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProductId = 1,
                            Quantity = 1,
                            ShoppingCartId = 1
                        },
                        new
                        {
                            Id = 2,
                            ProductId = 3,
                            Quantity = 2,
                            ShoppingCartId = 1
                        });
                });

            modelBuilder.Entity("CampingStoreAPP.Models.ShoppingCart", b =>
                {
                    b.HasOne("CampingStoreAPP.Models.AppUserId", "User")
                        .WithMany("ShoppingCarts")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CampingStoreAPP.Models.ShoppingCartItem", b =>
                {
                    b.HasOne("CampingStoreAPP.Models.Product", "Product")
                        .WithMany("CartItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CampingStoreAPP.Models.ShoppingCart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("ShoppingCartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CampingStoreAPP.Models.AppUserId", b =>
                {
                    b.Navigation("ShoppingCarts");
                });

            modelBuilder.Entity("CampingStoreAPP.Models.Product", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("CampingStoreAPP.Models.ShoppingCart", b =>
                {
                    b.Navigation("CartItems");
                });
#pragma warning restore 612, 618
        }
    }
}
